import logging
import random

from lib.discrete_event_sim_components import Counter
from lib.link_model import calculate_link_budget
from lib.phy import airtime
from lib.radio_loss import payload_is_lost

NODENUM_BROADCAST = 0xFFFFFFFF

logger = logging.getLogger(__name__)

class MeshPacket:
    unique_packet_counter = Counter()
    asym_rng = random.Random(44) # same default seed as in lib/config.py

    @staticmethod
    def seed_asym_rng(seed):
        MeshPacket.asym_rng.seed(seed)

    @staticmethod
    def reset_packet_counter():
        MeshPacket.unique_packet_counter = Counter()

    def __init__(self, conf, nodes, origTxNodeId, destId, txNodeId, plen, seq, genTime, wantAck, isAck, requestId, now, connectivity_map, baseline_pathloss_matrix):
        """Create a packet and work out which nodes sense and receive it.

        `seq` is the mesh packet id, shared by every copy; `genTime` is the original's.
        """
        self.unique_packet_seq = MeshPacket.unique_packet_counter.get()
        self.conf = conf
        self.origTxNodeId = origTxNodeId
        self.destId = destId
        self.txNodeId = txNodeId
        self.wantAck = wantAck
        self.isAck = isAck
        self.seq = seq
        self.requestId = requestId
        self.genTime = genTime
        self.now = now
        self.nodes = nodes
        self.baseTxPower = int(self.conf.PTX)
        self.txpow = self.baseTxPower
        self.priorHopRssi = None
        self.priorHopSnr = None
        self.LplAtN = [0 for _ in range(self.conf.NR_NODES)]
        self.terrainLossAtN = [0 for _ in range(self.conf.NR_NODES)]
        self.clutterLossAtN = [0 for _ in range(self.conf.NR_NODES)]
        self.rssiAtN = [0 for _ in range(self.conf.NR_NODES)]
        self.sensedByN = [False for _ in range(self.conf.NR_NODES)] # nodes which may possibly sense this packet
        self.detectedByN = [False for _ in range(self.conf.NR_NODES)]
        self.sensed_node_ids = []
        self.detected_node_ids = []
        self.collidedAtN = [False for _ in range(self.conf.NR_NODES)]
        self.collisionReasonAtN = [None for _ in range(self.conf.NR_NODES)]
        self.receivedAtN = [False for _ in range(self.conf.NR_NODES)]
        self.phyLostAtN = [False for _ in range(self.conf.NR_NODES)]
        self.onAirToN = [True for _ in range(self.conf.NR_NODES)]
        self.phyLossDrawAtN = [0.0 for _ in range(self.conf.NR_NODES)]

        # configuration values
        self.sf = self.conf.current_preset["sf"]
        self.cr = self.conf.current_preset["cr"]
        self.bw = self.conf.current_preset["bw"]
        self.freq = self.conf.FREQ
        self.tx_node = next(n for n in nodes if n.nodeid == self.txNodeId)
        self.connectivity_map = connectivity_map
        self.baseline_pathloss_matrix = baseline_pathloss_matrix

        logger.debug(f"{self.now:.3f} Packet {self.unique_packet_seq} for msg {self.seq} generated by node {self.txNodeId}")
        if self.conf.PHY_LOSS_MODEL_ENABLED:
            for rx_node in nodes:
                if rx_node.nodeid != self.txNodeId:
                    self.phyLossDrawAtN[rx_node.nodeid] = random.random()

        self.packetLen = plen
        self.timeOnAir = airtime(self.conf, self.sf, self.cr, self.packetLen, self.bw)
        self.retryTimerAirtimeReady = False
        self.startTime = 0
        self.endTime = 0
        self.refresh_link_budgets()

        # Routing. A reliable broadcast gets fewer attempts than an acknowledged unicast, which
        # is what the firmware's two constants say; retransmissions counts the ones still left.
        self.maxRetransmissions = max(0, self.reliable_attempts(conf, destId) - 1)
        self.retransmissions = self.maxRetransmissions
        self.ackReceived = False
        self.hopLimit = self.tx_node.hopLimit

    @staticmethod
    def reliable_attempts(conf, destId):
        """Total sends including the first, for a packet addressed to `destId`."""
        if destId == NODENUM_BROADCAST:
            return conf.RELIABLE_BROADCAST_ATTEMPTS
        return conf.RELIABLE_UNICAST_ATTEMPTS

    def refresh_link_budgets(self):
        """Recompute receiver-side RF state for the current TX power.

        The path is unchanged; RSSI, CAD, sensitivity and PHY loss are not.
        """
        self.detected_node_ids = []
        for rx_node in self.nodes:
            if rx_node.nodeid == self.txNodeId:
                continue
            if (
                self.conf.ENABLE_CONNECTIVITY_MAP
                and not self.conf.MOVEMENT_ENABLED
                and self.txNodeId in self.connectivity_map
                and rx_node.nodeid not in self.connectivity_map[self.txNodeId]
            ):
                logger.debug(
                    f"{self.now:.3f} skipping {self.txNodeId} -> {rx_node.nodeid} computation. "
                    f"connectivity map: {self.connectivity_map[self.txNodeId]}"
                )
                self.rssiAtN[rx_node.nodeid] = float("-inf")
                self.detectedByN[rx_node.nodeid] = False
                continue
            budget = calculate_link_budget(
                self.conf,
                self.tx_node,
                rx_node,
                getattr(self.conf, "LINK_OFFSET", {}).get((self.txNodeId, rx_node.nodeid), 0),
                tx_power_dbm=self.txpow,
            )
            self.terrainLossAtN[rx_node.nodeid] = budget.terrain_loss_db
            self.clutterLossAtN[rx_node.nodeid] = budget.clutter_loss_db
            self.LplAtN[rx_node.nodeid] = budget.calibrated_path_loss_db
            self.rssiAtN[rx_node.nodeid] = budget.rssi_dbm
            self.detectedByN[rx_node.nodeid] = self.rssiAtN[rx_node.nodeid] >= self.conf.current_preset["cad_threshold"]
            if self.detectedByN[rx_node.nodeid]:
                self.detected_node_ids.append(rx_node.nodeid)
        self.refresh_phy_reception()

    def airtime_for_cr(self, cr):
        """Predict airtime if this packet is transmitted with a different CR."""
        return airtime(self.conf, self.sf, cr, self.packetLen, self.bw)

    def set_coding_rate(self, cr):
        """Change only physical CR and recompute airtime.

        An explicit-header packet carries CR in the PHY header, so payload bytes are unchanged.
        """
        self.cr = cr
        self.timeOnAir = self.airtime_for_cr(cr)
        self.refresh_phy_reception()

    def set_tx_power(self, tx_power_dbm):
        """Change temporary TX power and recompute RF visibility.

        A per-transmission reduction only; baseTxPower stays the region's.
        """
        self.txpow = int(tx_power_dbm)
        self.refresh_link_budgets()

    def refresh_phy_reception(self):
        """Recompute payload-loss state after the selected CR changes.

        Sensitivity still gates reception: a stronger CR cannot resurrect an unheard preamble.
        """
        self.sensed_node_ids = []
        for rx_node_id, rssi in enumerate(self.rssiAtN):
            if rx_node_id == self.txNodeId:
                continue

            self.sensedByN[rx_node_id] = rssi >= self.conf.current_preset["sensitivity"]
            if self.sensedByN[rx_node_id]:
                self.sensed_node_ids.append(rx_node_id)
            self.phyLostAtN[rx_node_id] = False

            if self.sensedByN[rx_node_id]:
                self.phyLostAtN[rx_node_id] = payload_is_lost(
                    self.conf,
                    rssi,
                    self.cr,
                    self.packetLen,
                    self.phyLossDrawAtN[rx_node_id],
                )


class MeshMessage:
    def __init__(self, origTxNodeId, destId, genTime, seq):
        self.origTxNodeId = origTxNodeId
        self.destId = destId
        self.genTime = genTime
        self.seq = seq
        self.endTime = 0
